### ISSUE TITLE
platform_manifest_twrp_aosp is no work

### ISSUE THREAD

**Issue by RC1844** [minimal-manifest-twrp/platform_manifest_twrp_aosp#1]
https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp

~~~
[ 76% 216/282] including external/libaom/Android.mk ...
[ 76% 217/282] including external/libncurses/Android.mk ...
[ 77% 218/282] including external/magisk-prebuilt/Android.mk ...
[ 77% 219/282] including external/nano/Android.mk ...
[ 78% 220/282] including external/openssh/Android.mk ...
[ 78% 221/282] including external/robolectric-shadows/Android.mk ...
[ 78% 222/282] including external/vixl/Android.mk ...
[ 79% 223/282] including frameworks/base/Android.mk ...
FAILED: 
In file included from external/vixl/Android.mk:69:
In file included from frameworks/base/Android.mk:77:
frameworks/base/services/core/xsd/vts/Android.mk:22: error: test/vts/tools/build/Android.host_config.mk: No such file or directory
22:58:17 ckati failed with: exit status 1
Error: Process completed with exit code 1.
~~~

**Comment by RC1844** [comment]
> @RC1844 Works fine here. You have to make sure you do a repo sync right before building to ensure that dummy Android.mk file replaces the one that throws the above error.

The test I did on github Actions.After adding forced replacement file, it works normally.

**Comment by CaptainThrowback** [comment]
With Github actions, you have to add a repo sync before you do the mka command, to make sure the file gets replaced.

See here for reference: https://github.com/hraj9258/twrp_phoenix/blob/a11/.github/workflows/main.yml#L50-L63

**Comment by RC1844** [comment]
thank you

**Comment by MartinX3** [comment]
> > @RC1844 Works fine here. You have to make sure you do a repo sync right before building to ensure that dummy Android.mk file replaces the one that throws the above error.
> 
> The test I did on github Actions.After adding forced replacement file, it works normally.

@RC1844 actions has enough free storage space to compile twrp without aborting?

**Comment by RC1844** [comment]
@MartinX3 you can see : https://github.com/RC1844/Actions-Build-TWRP-For-Begonia/actions/runs/1013833785

**Comment by MartinX3** [comment]
@RC1844 thank you :)
I thought there is a storage or compilation time limit in the free actions plan

**Comment by RC1844** [comment]
@MartinX3 There are restrictions, but enough

**Comment by Aarqw12** [comment]
repo init --depth=1 --groups=all,-notdefault,-device,-darwin,-x86,-mips -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11

git clone https://github.com/Aarqw12/twrp_lena.git --depth=1 --single-branch device/sony/pdx213

[ 79% 225/284] including frameworks/base/Android.mk ...
FAILED:
In file included from external/wpa_supplicant_8/Android.mk:3:
In file included from frameworks/base/Android.mk:77:
frameworks/base/core/xsd/vts/Android.mk:22: error: test/vts/tools/build/Android.host_config.mk: No such file or directory
01:09:45 ckati failed with: exit status 1

by forced replacement file what do you mean ?

**Comment by MartinX3** [comment]
@Aarqw12 Please take a look at https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/issues/1#issuecomment-876814849
