### ISSUE TITLE
new gcc additions cause repo init fail

### ISSUE THREAD

**Issue by ghost** [minimal-manifest-twrp/platform_manifest_twrp_aosp#11]
repo init --depth=1 https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp -b twrp-12.1
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: manifest 'default.xml' not available
fatal: duplicate path prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 in /home/m/AndroidDev/twrp/.repo/manifests/default.xml

something isn't right here

**Comment by CaptainThrowback** [comment]
Should be fixed via https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/commit/6f21460bdb79d3360dfa5cf3b614b6b2edc942d5

Please confirm, and if fixed, close.
