### ISSUE TITLE
Could not find ui.xml for TW_THEME: not set

### ISSUE THREAD

**Issue by abhishek-junghare** [minimal-manifest-twrp/platform_manifest_twrp_aosp#16]
Could not find ui.xml for TW_THEME: not set

I have set `portrait_hdpi` in boardconfig.mk, but the issue persists.

**Comment by qnorsten** [comment]
I have the same problem with the 12.1 branch when trying to build for kebab.

**Comment by allex2** [comment]
See the error logs. You have the wrong source folder paths. Rename folders.

**Comment by mathew2214** [comment]
i am also having this issue. no error logs give any helpful information

**Comment by sanjay-29-29** [comment]
I was also having this issue but I fixed it by deleting the twrp repo and syncing it again by using repo sync -j5 --current-branch --no-clone-bundle --no-tags

**Comment by Maxon1652** [comment]
> Could not find ui.xml for TW_THEME: not set
> 
> I have set `portrait_hdpi` in boardconfig.mk, but the issue persists.

**Comment by Ayanokouji210** [comment]
I also met this problem with twrp branch android-12, I fixed this by edit  ./gui/libguitwrp_defaults.go
in this file there is 
func determineTheme(ctx android.BaseContext) string {}
and by edit guiWidth and guiHeight according to your device ,you can solve the problem

**Comment by kalehrl** [comment]
This works for Android 11 TWRP tree but in Android 9, there is no libguitwrp_defaults.go file. How can this be solved in Android 9?

**Comment by MartinX3** [comment]
Please use this repo for Android 9
https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni/tree/twrp-9.0

**Comment by kalehrl** [comment]
That's the one I used.

**Comment by MartinX3** [comment]
This issue tracker is for android 11 and 12.1.
