### ISSUE TITLE
error: c/android_bootable_recovery/+/5405/fscrypt:wip/Android.bp:51:1: module "soong-libaosprecovery_defaults" already defined

### ISSUE THREAD

**Issue by hejiYT** [minimal-manifest-twrp/platform_manifest_twrp_aosp#17]
![Screenshot_2022-05-17-23-24-00-49_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/65885744/168848663-fff0893f-e40c-4f52-9e23-2115f5476948.jpg)
I need your help!

**Comment by hungphan2001** [comment]
rm -rf c 
after rebuilding

**Comment by hungphan2001** [comment]
> ![Screenshot_2022-05-17-23-24-00-49_3d419158bad5872c40592a6c9956e692](https://user-images.githubusercontent.com/65885744/168848663-fff0893f-e40c-4f52-9e23-2115f5476948.jpg) I need your help!

rm -rf c 
after rebuilding

**Comment by DaDDevil** [comment]
it's ok
