### ISSUE TITLE
README.md mistake

### ISSUE THREAD

**Issue by electimon** [minimal-manifest-twrp/platform_manifest_twrp_aosp#19]
repo init --depth=1 -u git@github.com:minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
Downloading Repo source from https://gerrit.googlesource.com/git-repo
Enter passphrase for key '/home/jenkins/.ssh/id_ed25519':

Perhaps you should switch that to https instead of ssh...

**Comment by MartinX3** [comment]
Thank you!

**Comment by Maxon1652** [comment]
> repo init --depth=1 -u git@github.com:minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
> Downloading Repo source from https://gerrit.googlesource.com/git-repo
> Enter passphrase for key '/home/jenkins/.ssh/id_ed25519':
> 
> Perhaps you should switch that to https instead of ssh...

**Comment by Maxon1652** [comment]
> repo init --depth=1 -u git@github.com:minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-12.1
> Downloading Repo source from https://gerrit.googlesource.com/git-repo
> Enter passphrase for key '/home/jenkins/.ssh/id_ed25519':
> 
> Perhaps you should switch that to https instead of ssh...
