### ISSUE TITLE
Can't get it to compile on Samsung A12

### ISSUE THREAD

**Issue by edward0181** [minimal-manifest-twrp/platform_manifest_twrp_aosp#2]
For some strange reason, I can't get it to compile on AOSP android 11. When I use the manifests for omni (android 10) all is ok, can compile just fine. On this AOSP manifest, it just hang after including prebuilt kernel with ninja: no job to do.

Is the manifest still not complete, or am I missing something?
Device tree is here: https://github.com/edward0181/twrp_samsung_a12
but it just doesn't to work.

**Comment by MartinX3** [comment]
@edward0181 Any logs? :P

**Comment by edward0181** [comment]
Coming asap. Just syncing android 11 manifests again as I was working on 10 omni source

**Comment by edward0181** [comment]
[dumpvars-soong.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832167/dumpvars-soong.txt)
[ninja_log.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832168/ninja_log.txt)
[soong.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832169/soong.txt)

here are some logs.

**Comment by edward0181** [comment]
[AndroidProducts.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832190/AndroidProducts.txt)
[BoardConfig.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832191/BoardConfig.txt)
[device.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832192/device.txt)
[twrp_a12.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832194/twrp_a12.txt)

and makefiles under device dir

WOuld you be great if you could help me out.
Thanks

**Comment by ghost** [comment]
> [dumpvars-soong.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832167/dumpvars-soong.txt)
> [ninja_log.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832168/ninja_log.txt)
> [soong.txt](https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp/files/6832169/soong.txt)
> 
> here are some logs.

Do you building from CI? As the logs said `Operation not permitted` and the workdir is `/run`, common path in CI.

**Comment by edward0181** [comment]
Indeed I am using CL. My servers have a much better bandwidth hihi. What should working dir be set to?

**Comment by ghost** [comment]
The working dir is not too affecting the build, except 1) Your user is root 2) Your directory path is /root. Using root for Android build is highly not recommended.

My first tip is to change CI. Use CirrusCI (nah not a promotion) or GitHub Actions **Better With Custom Docker Image**

**Comment by edward0181** [comment]
Well that could makes sense. Will add another user and resync. Is gonna take me some time. Never had this problem on Omni source though. 

> The working dir is not too affecting the build, except 1) Your user is root 2) Your directory path is /root. Using root for Android build is highly not recommended.
> 
> 
> 
> My first tip is to change CI. Use CirrusCI (nah not a promotion) or GitHub Actions **Better With Custom Docker Image**

**Comment by ghost** [comment]
Furthermore, I can help you build the TWRP. As I have much free time. Using CirrusCI. Just _knock the door_ if you want 😁

**Comment by edward0181** [comment]
Well tried with other then root user env but still in vain. Always end with ninja telling no job left.

**Comment by edward0181** [comment]
![image](https://user-images.githubusercontent.com/6586180/126045903-bca382bb-b089-43b5-b9ae-0627f62b5383.jpeg)
These mention no branch

**Comment by edward0181** [comment]
Well made it too work. But now the bloody kernel fails to boot up in emulator. 

Back to drawing board.

**Comment by xiahuaijia** [comment]
Did you solve this problem, I also encountered the same problem

```
wildcard(out/target/product/camellia/clean_steps.mk) was changed, regenerating...
ninja: no work to do.

#### build completed successfully (16 seconds) ####
```

**Comment by edward0181** [comment]
> Did you solve this problem, I also encountered the same problem
> 
> ```
> wildcard(out/target/product/camellia/clean_steps.mk) was changed, regenerating...
> ninja: no work to do.
> 
> #### build completed successfully (16 seconds) ####
> ```

Nope, dinna have the time the spare just yet. all works under android 10 on the OMNI branch, but not under the AOSP11 branch, strangely.
And I can't test my twrp10 build in the emulator, as it donna like the ramdisk partitions of Samsung devices.

**Comment by edward0181** [comment]
Newest error I'm getting:

`
FAILED: out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
Outputs: out/soong/build.ninja
Error: exited with code: 1
Command: out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Output:
[31merror:[0m frameworks/base/core/res/Android.bp:49:1: module "framework-res-package-jar" variant "android_common": path dependency ":framework-res{.export-package.apk}": unsupported module reference tag ".export-package.apk"

`

**Comment by bxlentpartyon** [comment]
I'm running into the same problem with:
```
ninja: no work to do.

#### build completed successfully (6 seconds) ####
```
I don't see any notable errors anywhere, just that ninja can't find anything to do.  I can supply logs, etc., if anyone needs anything specific.  I'm new to building Android/TWRP, so I don't know what others would find useful :)

**Comment by ghost** [comment]
With these problems I'm sure it must be the source problem.

**Comment by ghost** [comment]
Well we should wait more longer since A11 TWRP source is still in beta stage.

**Comment by bxlentpartyon** [comment]
After digging around for a while, I found this in `build/make/core/board_config.mk`:
```# Are we building a recovery image
BUILDING_RECOVERY_IMAGE :=
ifeq ($(BOARD_USES_RECOVERY_AS_BOOT),true)
  BUILDING_RECOVERY_IMAGE := true
else ifeq ($(PRODUCT_BUILD_RECOVERY_IMAGE),)
  ifdef BOARD_RECOVERYIMAGE_PARTITION_SIZE
    ifeq (,$(filter true, $(TARGET_NO_KERNEL) $(TARGET_NO_RECOVERY)))
      BUILDING_RECOVERY_IMAGE := true
    endif
  endif
else ifeq ($(PRODUCT_BUILD_RECOVERY_IMAGE),true)
  BUILDING_RECOVERY_IMAGE := true
endif
.KATI_READONLY := BUILDING_RECOVERY_IMAGE
```
I added some debugging stuff in here, and it turned out that `BUILDING_RECOVERY_IMAGE` was never getting set to `true` during my build.  I took a look at the size of the `recovery` partition on the device:
```
gts7lwifi:/ $ ls -l /dev/block/by-name/recovery 
lrwxrwxrwx 1 root root 16 2019-04-12 05:57 /dev/block/by-name/recovery -> /dev/block/sda23
gts7lwifi:/ $ cat /proc/partitions | egrep 'sda23'            
 259        7      84852 sda23
```
Judging from what I can see on other partitions, that size is in 1K blocks, so I determined that the recovery partition size should be:
```
84852*1024 = 86888448
```
I'm not super confident that I'm exactly right there, as comparing the `/proc/partitions` output with what `df` shows doesn't totally match up, though `df` might show the size minus any filesystem metadata on the partition.

In any case, (very) long story short, adding:
```
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 86888448
```
To my `device/samsung/gts7lwifi/BoardConfig.mk` got the appropriate pieces to fall into place to get the build to do _something_.  Again, I'm not positive that I got that size right (though I'm also not sure if it really matters that much), and I also have no idea if what it builds will work at all, but it's at least trying to build now.

I hope this helps others who might be running into this same issue.

**Comment by ghost** [comment]
So the conclusion is:

1. We need to define our recovery partition size
2. Set `PRODUCT_BUILD_RECOVERY_IMAGE`

Am I right?

**Comment by bxlentpartyon** [comment]
I tried setting `PRODUCT_BUILD_RECOVERY_IMAGE := true` and that didn't seem to have any effect.  The trick seemed to be to set `BOARD_RECOVERYIMAGE_PARTITION_SIZE`.

**Comment by ghost** [comment]
Understood. Glad you can fix the error.

**Comment by edward0181** [comment]
> I tried setting `PRODUCT_BUILD_RECOVERY_IMAGE := true` and that didn't seem to have any effect.  The trick seemed to be to set `BOARD_RECOVERYIMAGE_PARTITION_SIZE`.

Can confirm that this does the trick. 
Running compile now. Thanks for the help.

**Comment by ghost** [comment]
Don't close this issue, so devs can take a look in here easily.

**Comment by MartinX3** [comment]
If the same device tree did work without on 10, it must be a new google requirement :)

And maybe this helps you
https://android-review.googlesource.com/c/platform/build/+/951796/

**Comment by edward0181** [comment]
It did work on android 10 indeed. Now solved by using this line again. Thanks. Now hoping it'll boot up. Thanks

**Comment by bxlentpartyon** [comment]
> If the same device tree did work without on 10, it must be a new google requirement :)

That's kinda what I was thinking.  I wouldn't call this a real bug, just something we didn't know was a requirement when building the latest stuff.

> And maybe this helps you
> https://android-review.googlesource.com/c/platform/build/+/951796/

Ah, that would explain it!  I should've done a `git blame` to see if this was a recent change :)

**Comment by ghost** [comment]
But we should modify the logic. We don't need any of those. Just build boot and recovery is enough.

**Comment by MartinX3** [comment]
It seems to be a requirement for devices starting with android 10 on the market, which means they have dynamic partitions support.

**Comment by edward0181** [comment]
Indeed. If you build with dynamic partitions it'll work just fine. Now need to get encryption off and keep twrp from being deleted from recovery I'll be done.

**Comment by MartinX3** [comment]
Nice, then everything works. :)

**Comment by dragonpt** [comment]
Late to the party, just wanna say thanks... indeed adding `BOARD_RECOVERYIMAGE_PARTITION_SIZE` did the trick.

was also having
`ninja: no work to do.`
 `#### build completed successfully ` but no actual recovery image on /OUT

Same device tree worked just fine on 10, glad i checked this... You saved me some hours of debug ;p

cheers

**Comment by UDPSendToFailed** [comment]
Thanks guys! Had the same problem with `ninja: no work to do`, adding BOARD_RECOVERYIMAGE_PARTITION_SIZE to my BoardConfig.mk solved it.

**Comment by infinixs5lite** [comment]
> Furthermore, I can help you build the TWRP. As I have much free time. Using CirrusCI. Just _knock the door_ if you want 😁

Ok can u pls
