### ISSUE TITLE
WHAT IS WRONG WITH YOU: MISSING LIBRARY

### ISSUE THREAD

**Issue by bgman111111** [minimal-manifest-twrp/platform_manifest_twrp_aosp#21]
cd "$(dirname "out/soong/.bootstrap/bin/soong_build")" && BUILDER="$PWD/$(basename "out/soong/.bootstrap/bin/soong_build")" && cd / && env -i "$BUILDER"     --top "$TOP"     --out "out/soong"     -n "out"     -d
 "out/soong/build.ninja.d"     -t -l out/.module_paths/Android.bp.list -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja --available_env out/soong/soong.environment.available --used_env o
ut/soong/soong.environment.used Android.bp
error: hardware/interfaces/tests/bar/1.0/Android.bp:12:1: "android.hardware.tests.bar@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/broadcastradio/1.1/Android.bp:12:1: "android.hardware.broadcastradio@1.1-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/neuralnetworks/1.3/Android.bp:12:1: "android.hardware.neuralnetworks@1.3-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/tests/msgq/1.0/Android.bp:12:1: "android.hardware.tests.msgq@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/power/stats/1.0/Android.bp:12:1: "android.hardware.power.stats@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/camera/device/3.7/Android.bp:12:1: "android.hardware.camera.device@3.7-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/media/1.0/Android.bp:12:1: "android.hardware.media@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/audio/common/6.0/Android.bp:12:1: "android.hardware.audio.common@6.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/audio/effect/6.0/Android.bp:12:1: "android.hardware.audio.effect@6.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: hardware/interfaces/usb/1.3/Android.bp:12:1: "android.hardware.usb@1.3-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: vendor/qcom/opensource/interfaces/display/demura/2.0/Android.bp:3:1: "vendor.qti.hardware.display.demura@2.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
error: system/libhidl/transport/safe_union/1.0/Android.bp:12:1: "android.hidl.safe_union@1.0-vts.fuzzer" depends on undefined module "vts_proto_fuzzer_default"
02:19:07 soong bootstrap failed with: exit status 1

#### failed to build some targets (43 seconds) ####

other

[ 78% 245/312] including bootable/recovery/Android.mk ...
bootable/recovery/prebuilt/Android.mk:405: warning: vendor_hw:  bootable/recovery/prebuilt/relink.sh out/target/product/RMXS710/recovery/root/vendor/bin/hw 
[ 95% 299/312] including system/sepolicy/Android.mk ...
system/sepolicy/Android.mk:57: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
system/sepolicy/Android.mk:62: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR has been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
FAILED: ninja: 'out/target/product/RMXS710/obj/SHARED_LIBRARIES/libkeystore_binder_intermediates/libkeystore_binder.so.toc', needed by 'out/target/product/RMXS710/obj/SHARED_LIBRARIES/libtwrpfscrypt_intermediate
s/LINKED/libtwrpfscrypt.so', missing and no known rule to make it
01:55:45 ninja failed with: exit status 1

#### failed to build some targets (01:23 (mm:ss)) ####

im not developer can somoene help me put entire TWRP for android 12. As making minimal is not working and this is device tree //github.com/SathamHussainM/device_realme_RMXS710-twrp.git usb and mtp is not working and on compile it give missing drivers. very bad

**Comment by xxroot** [comment]
I also encountered the same problem. Have you solved it

**Comment by BlackMesa123** [comment]
@bgman111111 @xxroot 

As stated in the README of this repo, you must apply these two patches in your build environment in order to fix any build errors caused by `TW_INCLUDE_CRYPTO`:
- [fscrypt: wip](https://gerrit.twrp.me/c/android_bootable_recovery/+/5405)
- [fscrypt: move functionality to libvold](https://gerrit.twrp.me/c/android_system_vold/+/5540)
