### ISSUE TITLE
fatal: couldn't find remote ref refs/heads/twrp-10

### ISSUE THREAD

**Issue by KJS1212** [minimal-manifest-twrp/platform_manifest_twrp_aosp#27]
dolphinp1-twrp> repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-10
Downloading Repo source from https://gerrit.googlesource.com/git-repo
repo: Updating release signing keys to keyset ver 2.3

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
manifests: sleeping 4.0 seconds before retrying

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
jo@UNKNOWN:~/dolphinp1-twrp> repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-10
Downloading Repo source from https://gerrit.googlesource.com/git-repo

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
manifests: sleeping 4.0 seconds before retrying

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
jo@UNKNOWN:~/dolphinp1-twrp> repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-10

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
manifests: sleeping 4.0 seconds before retrying

manifests:
fatal: couldn't find remote ref refs/heads/twrp-10
fatal: cannot obtain manifest https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git

**Comment by MartinX3** [comment]
The branch doesn't exist.
