### ISSUE TITLE
Zulip link in README is dead

### ISSUE THREAD

**Issue by daboross** [minimal-manifest-twrp/platform_manifest_twrp_aosp#3]
Title says it all. Looks like there are commits from a month ago, so I'm assuming the project isn't dead.

Is the zulip still alive, and if so, could you post a new sign-up link?

I tried joining the #twrp channel on Libera IRC, and it *was* dead, so I'm hoping to find another active community.

**Comment by MartinX3** [comment]
@daboross Thank you very much.
Sadly the link expires automatically and then it can happen that we forget to update the README.
I made a ticket, but sadly I got no response until now: https://github.com/zulip/zulip/issues/19126

We are happy if we get hints by the community to fix that. Thank you. :)

**Comment by z3ntu** [comment]
@MartinX3 The link is expired again

From https://zulip.com/help/invite-new-users : 
> Note that on most Zulip servers (including Zulip Cloud), email invitations and reusable invitation links expire 10 days after they are sent.

That also matches the value in the source code https://github.com/zulip/zulip/blob/aeb0dc726967eae6c0ec8d4c5fa084cd2ca5e1c5/zproject/default_settings.py#L349

**Comment by MartinX3** [comment]
@z3ntu Thank you very much. :)
The link got updated.

**Comment by MartinX3** [comment]
ISSUE: https://github.com/zulip/zulip/issues/19680
PR: https://github.com/zulip/zulip/pull/19761
