### ISSUE TITLE
error: PRODUCT_STATIC_BOOT_CONTROL_HAL is obsolete. Use shared library module instead. See https://android.googlesource.com/platform/build/+/master/Changes.md#PRODUCT_STATIC_BOOT_CONTROL_HAL. 18:18:26 dumpvars failed with: exit status 1

### ISSUE THREAD

**Issue by xiaoxigg** [minimal-manifest-twrp/platform_manifest_twrp_aosp#34]
The prompt expires

How to solve this problem
![111](https://user-images.githubusercontent.com/103127186/230767541-a9d47179-4616-4f64-8330-ea1e9227b3a5.png)
![222](https://user-images.githubusercontent.com/103127186/230767548-67528653-a5e4-4912-a7ec-d868ff29f6be.png)

**Comment by thinksecure** [comment]
Does anyone know how to fix this?
I got the same problem.
