### ISSUE TITLE
warning: vendor_hw:  bootable/recovery/ prebuilt/relink.sh out/target/product/selene/recovery/root/vendor/bin/hw 

### ISSUE THREAD

**Issue by xiaoxigg** [minimal-manifest-twrp/platform_manifest_twrp_aosp#38]
aosp 12.1    **How to resolve this warning** 

Here are my variables

RECOVERY_VENDOR_HW_BINARY_FILES := \
   xiaomi/selene/vendor/bin/hw/*

**Comment by MartinX3** [comment]
Missing full log (no screenshot)
Missing link to source code (device tree)

**Comment by xiaoxigg** [comment]
Generated by my device tree twrpdtgen
