### ISSUE TITLE
repo init error

### ISSUE THREAD

**Issue by scarlet-glass** [minimal-manifest-twrp/platform_manifest_twrp_aosp#4]
scarlet-glass@scarlet-glass-PC:~/twrp$ repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b twrp-11
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 2, done
remote: Finding sources: 100% (54/54)
remote: Total 54 (delta 27), reused 54 (delta 27)
展开对象中: 100% (54/54), 完成.
Downloading manifest from git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
fatal: 读取错误: 连接被对方重设
fatal: 协议错误：坏的包头
manifests: sleeping 4.0 seconds before retrying
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
fatal: 读取错误: 连接被对方重设
fatal: 协议错误：坏的包头
fatal: cannot obtain manifest git://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git

**Comment by MartinX3** [comment]
I sadly can't reproduce your issue.

Since you're from china maybe your "great" firewall is blocking it?

**Comment by shuxiangfan** [comment]
Please sync repo through VPN if you are in China
如果你在中国，请通过VPN同步源码

**Comment by MartinX3** [comment]
No response from the TA, so I'll close it. :)

**Comment by KJS1212** [comment]
I am having the exact same issue but I'm in the UK
