### ISSUE TITLE
Error: You are building on a case-insensitive filesystem.

### ISSUE THREAD

**Issue by isrgish** [minimal-manifest-twrp/platform_manifest_twrp_aosp#42]
I'm trying to build my TWRP on ubuntu running with WSL2 on Windows. I get an error:

`"You are building on a case-insensitive filesystem. Please move your source tree to a case-sensitive filesystem."`

I set the folder that the repo is in to case sensitive but I still get this error.

Is there a way that I can run this? Maybe some way to force it to see it as a case sensitive system. Or maybe force it to compile anyway.

**Comment by MartinX3** [comment]
Not a TWRP specific issue.
Please look at the WSL issue tracker.

**Comment by isrgish** [comment]
To answer my own question for someone who has the same problem.
I had setup my repo on the windows filesystem and windows isn't case sensitive.
I changed the whole repo into my home directory which is case sensitive (at least in WSL 2) and it worked perfectly.

You can also set a folder on windows to be case sensitive (google it) probably this should also work but I didn't try it.
