### ISSUE TITLE
branch twrp-14 build failed

### ISSUE THREAD

**Issue by FTS427** [minimal-manifest-twrp/platform_manifest_twrp_aosp#60]
`[ 97% 386/394] converting Android.bp files to BUILD files at /home/fts427/Android/build_source
FAILED: /home/fts427/Android/build_source/twrp_build/OUT/soong/bp2build_files_marker
cd "$(dirname "/home/fts427/Android/build_source/twrp_build/OUT/host/linux-x86/bin/soong_build")" && BUILDER="$PWD/$(basename "/home/fts427/Android/build_source/twrp_build/OUT/host/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"     --soong_out "/home/fts427/Android/build_source/twrp_build/OUT/soong"     --out "/home/fts427/Android/build_source/twrp_build/OUT"     --bp2build_marker /home/fts427/Android/build_source/twrp_build/OUT/soong/bp2build_files_marker --globListDir bp2build_files --globFile /home/fts427/Android/build_source/twrp_build/OUT/soong/globs-bp2build_files.ninja -t -l /home/fts427/Android/build_source/twrp_build/OUT/.module_paths/Android.bp.list --available_env /home/fts427/Android/build_source/twrp_build/OUT/soong/soong.environment.available --used_env /home/fts427/Android/build_source/twrp_build/OUT/soong/soong.environment.used.bp2build_files Android.bp
error: hardware/interfaces/automotive/remoteaccess/hal/default/test/Android.bp:19:1: "RemoteAccessServiceUnitTest" depends on undefined module "vhalclient_defaults".
Or did you mean ["canhalconfigurator" "hardening-benchmark" "vhal_v2_0_defaults"]?
error: hardware/interfaces/automotive/remoteaccess/hal/default/Android.bp:21:1: "remote-access-hal-defaults" depends on undefined module "vhalclient_defaults".
Or did you mean ["canhalconfigurator" "hardening-benchmark" "vhal_v2_0_defaults"]?
error: hardware/google/aemu/base/Android.bp:10:1: "gfxstream_base" depends on undefined module "gfxstream_defaults".
Or did you mean ["CtsDreamsTestCases" "StreamingProtoTest"]?
error: hardware/interfaces/neuralnetworks/1.0/utils/Android.bp:26:1: "neuralnetworks_utils_hal_1_0" depends on undefined module "neuralnetworks_utils_defaults".
Or did you mean ["libneuralnetworks.vndk.31.arm" "libneuralnetworks.vndk.31.x86" "libneuralnetworks.vndk.32.arm" "libneuralnetworks.vndk.32.x86" "libneuralnetworks.vndk.33.arm" "libneuralnetworks.vndk.33.x86"]?
error: tools/loganalysis/Android.bp:19:1: "loganalysis" depends on undefined module "tradefed_defaults".
Or did you mean ["storaged_defaults" "tracefast-defaults"]?
error: packages/modules/AdServices/adservices/libraries/collectors-helper/adservices/test/Android.bp:19:1: "adservices-collectors-helper-test" depends on undefined module "tradefed_errorprone_defaults".
Or did you mean ["CtsCredentialManagerTestCases" "CtsFrameRateOverrideTestCases" "CtsThreadLocalRandomHostTest" "ftrace_synthetic_events.conf" "getrandom_test_tests_normal" "getrandom_test_tests_rdrand" "surfaceflinger_binary_sources" "surfaceflinger_fuzz_defaults" "surfaceflinger_layer_fuzzer" "threadnetwork_service_default"]?
error: packages/modules/AdServices/adservices/libraries/collectors-helper/tests/Android.bp:19:1: "AdservicesCollectorsHelperTest" depends on undefined module "tradefed_errorprone_defaults".
Or did you mean ["CtsCredentialManagerTestCases" "CtsFrameRateOverrideTestCases" "CtsThreadLocalRandomHostTest" "ftrace_synthetic_events.conf" "getrandom_test_tests_normal" "getrandom_test_tests_rdrand" "surfaceflinger_binary_sources" "surfaceflinger_fuzz_defaults" "surfaceflinger_layer_fuzzer" "threadnetwork_service_default"]?
error: hardware/interfaces/neuralnetworks/1.3/utils/Android.bp:26:1: "neuralnetworks_utils_hal_1_3" depends on undefined module "neuralnetworks_utils_defaults".
Or did you mean ["libneuralnetworks.vndk.31.arm" "libneuralnetworks.vndk.31.x86" "libneuralnetworks.vndk.32.arm" "libneuralnetworks.vndk.32.x86" "libneuralnetworks.vndk.33.arm" "libneuralnetworks.vndk.33.x86"]?
error: hardware/interfaces/neuralnetworks/1.1/utils/Android.bp:26:1: "neuralnetworks_utils_hal_1_1" depends on undefined module "neuralnetworks_utils_defaults".
Or did you mean ["libneuralnetworks.vndk.31.arm" "libneuralnetworks.vndk.31.x86" "libneuralnetworks.vndk.32.arm" "libneuralnetworks.vndk.32.x86" "libneuralnetworks.vndk.33.arm" "libneuralnetworks.vndk.33.x86"]?
error: hardware/interfaces/neuralnetworks/utils/common/Android.bp:26:1: "neuralnetworks_utils_hal_common" depends on undefined module "neuralnetworks_utils_defaults".
Or did you mean ["libneuralnetworks.vndk.31.arm" "libneuralnetworks.vndk.31.x86" "libneuralnetworks.vndk.32.arm" "libneuralnetworks.vndk.32.x86" "libneuralnetworks.vndk.33.arm" "libneuralnetworks.vndk.33.x86"]?
17:02:50 soong bootstrap failed with: exit status 1`

twrp device tree repo link: https://github.com/QuantumLS-Studio/twrp_device_lenovo_X306

**Comment by cachiusa** [comment]
Please don't report device related problems here, post this issue in the Zulip chat instead

**Comment by FTS427** [comment]
ok...this problem seemed to be sovled by `export ALLOW_MISSING_DEPENDENCES=true`, but here's another new problem that doesn't relat my device tree
![图片](https://github.com/user-attachments/assets/f98464eb-b21a-44e4-bd43-d20d665b8971)
